//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.Everything.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.Everything.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set text in clipboard.
        /// </summary>
        public static string clipboard_failed {
            get {
                return ResourceManager.GetString("clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        public static string Context {
            get {
                return ResourceManager.GetString("Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure context menu options and order.
        ///0_Open folder, 1_Run as Admin, 2_Run as User, 3_Copy, 4_Copy Path, 5_Open in Console, 6_Open in custom program.
        /// </summary>
        public static string Context_Description {
            get {
                return ResourceManager.GetString("Context_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy .
        /// </summary>
        public static string copy_file {
            get {
                return ResourceManager.GetString("copy_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path .
        /// </summary>
        public static string copy_path {
            get {
                return ResourceManager.GetString("copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+C).
        /// </summary>
        public static string copy_shortcut {
            get {
                return ResourceManager.GetString("copy_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ctrl+Alt+C).
        /// </summary>
        public static string copy_shortcutAlt {
            get {
                return ResourceManager.GetString("copy_shortcutAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch argument.
        /// </summary>
        public static string CustomArg {
            get {
                return ResourceManager.GetString("CustomArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument to pass to the program when launching. [$P=path of the selected result ].
        /// </summary>
        public static string CustomArg_Description {
            get {
                return ResourceManager.GetString("CustomArg_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Program.
        /// </summary>
        public static string CustomProgram {
            get {
                return ResourceManager.GetString("CustomProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to a external program that&apos;ll open the selected result.
        /// </summary>
        public static string CustomProgram_Description {
            get {
                return ResourceManager.GetString("CustomProgram_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviroment Variables.
        /// </summary>
        public static string EnvVar {
            get {
                return ResourceManager.GetString("EnvVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand enviroment variables, such as %appdata%, so that they work properly at the cost of query time..
        /// </summary>
        public static string EnvVar_Description {
            get {
                return ResourceManager.GetString("EnvVar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Everything if not installed.
        /// </summary>
        public static string Everything_ini {
            get {
                return ResourceManager.GetString("Everything_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is not running.
        /// </summary>
        public static string Everything_not_running {
            get {
                return ResourceManager.GetString("Everything_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything64.exe.
        /// </summary>
        public static string EverythingPath {
            get {
                return ResourceManager.GetString("EverythingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of Everything.exe if it&apos;s not installed in &quot;Program Files&quot;.
        /// </summary>
        public static string EverythingPath_Description {
            get {
                return ResourceManager.GetString("EverythingPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to open folder at.
        /// </summary>
        public static string folder_open_failed {
            get {
                return ResourceManager.GetString("folder_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Path.
        /// </summary>
        public static string Match_path {
            get {
                return ResourceManager.GetString("Match_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search path in additional to file/folder name..
        /// </summary>
        public static string Match_path_Description {
            get {
                return ResourceManager.GetString("Match_path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount of results to display in the results..
        /// </summary>
        public static string Max_Description {
            get {
                return ResourceManager.GetString("Max_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more....
        /// </summary>
        public static string more_results {
            get {
                return ResourceManager.GetString("more_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Everything and see the remaining results.
        /// </summary>
        public static string more_results_Subtitle {
            get {
                return ResourceManager.GetString("more_results_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder (Ctrl+Shift+E).
        /// </summary>
        public static string open_containing_folder {
            get {
                return ResourceManager.GetString("open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in console (Ctrl+Shift+C).
        /// </summary>
        public static string open_in_console {
            get {
                return ResourceManager.GetString("open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in custom program (Ctrl+N).
        /// </summary>
        public static string open_in_custom {
            get {
                return ResourceManager.GetString("open_in_custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get search results from Everything.
        /// </summary>
        public static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds prefix to all queries, so that you can always include certain filters/modifiers without typing it every time.
        ///Space is not added automatically between prfix and query..
        /// </summary>
        public static string Prefix_Description {
            get {
                return ResourceManager.GetString("Prefix_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview file content as icon, may cause freezing if file is not local..
        /// </summary>
        public static string Preview_Description {
            get {
                return ResourceManager.GetString("Preview_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Text.
        /// </summary>
        public static string QueryText {
            get {
                return ResourceManager.GetString("QueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected result can update query text. Helps display additional info, but may change display results..
        /// </summary>
        public static string QueryText_Description {
            get {
                return ResourceManager.GetString("QueryText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        public static string RegEx {
            get {
                return ResourceManager.GetString("RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable regular expression in search.
        ///Recommend using regex: in query instead of enabling this option.
        /// </summary>
        public static string RegEx_Description {
            get {
                return ResourceManager.GetString("RegEx_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator (Ctrl+Shift+Enter).
        /// </summary>
        public static string run_as_admin {
            get {
                return ResourceManager.GetString("run_as_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as different user (Ctrl+Shift+U).
        /// </summary>
        public static string run_as_user {
            get {
                return ResourceManager.GetString("run_as_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a result that opens Everything with the current query..
        /// </summary>
        public static string ShowMore_Description {
            get {
                return ResourceManager.GetString("ShowMore_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set result sorting method..
        /// </summary>
        public static string Sort_Description {
            get {
                return ResourceManager.GetString("Sort_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string SwapCopy {
            get {
                return ResourceManager.GetString("SwapCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Ctrl+C to copy file/folder, Ctrl+Alt+C to copy path..
        /// </summary>
        public static string SwapCopy_Description {
            get {
                return ResourceManager.GetString("SwapCopy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install new version of EverythingPowerToys?
        ///Clicking &apos;No&apos; will disable future notice for this version.
        ///
        ///Installed:		{0}
        ///Latest:		{1}.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
    }
}
