//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.Everything.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.Everything.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set text in clipboard.
        /// </summary>
        public static string clipboard_failed {
            get {
                return ResourceManager.GetString("clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path (Ctrl+C).
        /// </summary>
        public static string copy_path {
            get {
                return ResourceManager.GetString("copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Wait setting under PowerToys Run &gt; Everything.
        /// </summary>
        public static string enable_wait {
            get {
                return ResourceManager.GetString("enable_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Everything if not installed.
        /// </summary>
        public static string Everything_ini {
            get {
                return ResourceManager.GetString("Everything_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is not running.
        /// </summary>
        public static string Everything_not_running {
            get {
                return ResourceManager.GetString("Everything_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to open folder at.
        /// </summary>
        public static string folder_open_failed {
            get {
                return ResourceManager.GetString("folder_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder (Ctrl+Shift+E).
        /// </summary>
        public static string open_containing_folder {
            get {
                return ResourceManager.GetString("open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in console (Ctrl+Shift+C).
        /// </summary>
        public static string open_in_console {
            get {
                return ResourceManager.GetString("open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get search results from Everything.
        /// </summary>
        public static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator (Ctrl+Shift+Enter).
        /// </summary>
        public static string run_as_admin {
            get {
                return ResourceManager.GetString("run_as_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out before finishing the query.
        /// </summary>
        public static string timeout {
            get {
                return ResourceManager.GetString("timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert result at the top of the list..
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait - Wait longer for the query to finish..
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
