//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEsDBBQAAAAIAO2AMVjgH6MZ/RYAAHmYAAA+AAAARXZlcnl0aGluZy9Db21tdW5pdHkuUG93ZXJUb3lzLlJ1bi5QbHVnaW4uRXZlcnl0aGluZy5kZXBzLmpzb27tXFmTqsyWfe+I/g83ziv3k1GBjrgPqDggk+CEb0wCyiQz3vj+e6s1aFU5F3VOVfd9OeEpyJ251t65c2cC69///V//+MevKPUTxzNHamSZya//+ce/d3/d/t1XPXP73181nh61gsikwvCfEzOKncD/V0bUoF//fL4xdixfTdJof/ev3R//3l/6pQde6Lhqsm0hhLt/453554vJvr/4qMOzHb3esr2pFXhe6jtJWROD3IxGQRnXpNSviW5qOX6NzsyoTGzHt0Cohr9tu21tmKHpG6avO2b89tL2IufoURAHi6TWCgyT8lW3jJ24xpvJ/vdmO6Qdwu2IDuCfmx7GIptJsu09ro37NdbRdg22t9fgdw3kpHTNVhDW3piGa0gN+kszE7VW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base64zipKey {
            get {
                return ResourceManager.GetString("base64zipKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.7.0.
        /// </summary>
        internal static string versionKey {
            get {
                return ResourceManager.GetString("versionKey", resourceCulture);
            }
        }
    }
}
